### ISSUE TITLE
Errors during the ES query 

### ISSUE THREAD

**Issue by muttcg** [gbif/metrics#2]
```
Caused by: org.elasticsearch.index.query.QueryShardException: failed to create query: {
  "bool" : {
    "filter" : [
      {
        "term" : {
          "hasCoordinate" : {
            "value" : "TRUE",
            "boost" : 1.0
          }
        }
      }
    ],
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}
Caused by: java.lang.IllegalArgumentException: Can't parse boolean value [TRUE], expected [true] or [false]
```
Looks like here:
https://github.com/gbif/metrics/blob/e34afa5c26578f06577cb6784b8b72f6e16d516f/metrics-es/src/main/java/org/gbif/metrics/es/EsMetricsService.java#L172

We improved in occurrence:
https://github.com/gbif/occurrence/blob/f7723e4eff1fe63d637076add705e3e6334bf8c4/occurrence-search/src/main/java/org/gbif/occurrence/search/es/EsSearchRequestBuilder.java#L341

**Comment by ahakanzn** [comment]
deployed to prod
